import Anthropic from '@anthropic-ai/sdk';
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const SKILLS_DIR = './skills';

// 스킬 목록 수집
const skills = fs.readdirSync(SKILLS_DIR)
  .filter(d => fs.statSync(path.join(SKILLS_DIR, d)).isDirectory())
  .filter(d => fs.existsSync(path.join(SKILLS_DIR, d, 'SKILL.md')));

if (skills.length === 0) {
  console.error('No skills found');
  process.exit(1);
}

// 주차 기반 로테이션
const weekNumber = Math.floor(Date.now() / (7 * 24 * 60 * 60 * 1000));
const skillName = skills[weekNumber % skills.length];
const skillPath = path.join(SKILLS_DIR, skillName, 'SKILL.md');
const original = fs.readFileSync(skillPath, 'utf-8');

console.log(`Target skill: ${skillName}`);

// meta-improvements.md 수집 — 프로젝트들이 남긴 자가수정 제안
// (레포 내 docs/**/meta-improvements.md 파일 탐색)
let metaContext = '';
try {
  const metaFiles = execSync(
    'find . -path ./node_modules -prune -o -name "meta-improvements.md" -print',
    { encoding: 'utf-8' }
  ).trim().split('\n').filter(Boolean);

  if (metaFiles.length > 0) {
    const contents = metaFiles.map(f => {
      try { return `[${f}]\n${fs.readFileSync(f, 'utf-8')}`; }
      catch { return ''; }
    }).filter(Boolean).join('\n\n');

    if (contents) {
      metaContext = `\n\n## Meta Improvements from Past Tasks\n${contents}`;
      console.log(`Loaded meta-improvements from ${metaFiles.length} file(s)`);
    }
  }
} catch { /* meta-improvements 없으면 그냥 진행 */ }

// Claude API 호출 — web_search + meta-improvements 컨텍스트
const response = await client.beta.messages.create({
  model: 'claude-opus-4-7',
  max_tokens: 4096,
  betas: ['web-search-2025-03-05'],
  tools: [{ type: 'web_search_20250305', name: 'web_search' }],
  messages: [{
    role: 'user',
    content: `You are enhancing a skill file for a Claude Code skills repository (nova-skills).
Domain: Next.js frontend, NestJS backend, React Three Fiber 3D, AI agent protocols.

## Current Skill: ${skillName}

\`\`\`markdown
${original}
\`\`\`
${metaContext}

## Task
1. Search for the latest updates, patterns, or pitfalls in this skill's domain.
2. If meta-improvements context exists, incorporate MEDIUM/LOW level improvements — never touch CRITICAL/HIGH level rules.
3. Identify ONE specific enhancement that adds concrete value.
4. Make the minimal targeted change.

## Rules
- Frontmatter (name, description) must remain unchanged
- Description: "Use when..." triggering conditions only — no workflow summary
- Body content in Korean
- No version notes ("> v1.x: ...") in the body
- NEVER modify rules marked 🔴 CRITICAL or 🟠 HIGH
- One focused change only

Return ONLY the complete updated SKILL.md content with no explanation.`
  }]
});

const updated = response.content
  .filter(b => b.type === 'text')
  .map(b => b.text)
  .join('')
  .trim();

if (!updated || updated === original.trim()) {
  console.log('No changes — skipping PR');
  fs.appendFileSync(process.env.GITHUB_OUTPUT ?? '/dev/null', 'changed=false\n');
  process.exit(0);
}

fs.writeFileSync(skillPath, updated + '\n');
console.log(`Updated: ${skillPath}`);

const prBody = `## Weekly Skill Enhancement

**Skill:** \`${skillName}\`

Automatically enhanced with latest patterns via web search.${metaContext ? '\nMeta-improvements from past tasks incorporated (MEDIUM/LOW only).' : ''}

---
*Generated by [weekly-skill-enhancement workflow](../.github/workflows/weekly-skill-enhancement.yml)*`;

fs.writeFileSync('/tmp/pr-body.md', prBody);

const out = process.env.GITHUB_OUTPUT ?? '/dev/null';
fs.appendFileSync(out, `changed=true\n`);
fs.appendFileSync(out, `skill_name=${skillName}\n`);
