import Anthropic from '@anthropic-ai/sdk';
import fs from 'fs';
import path from 'path';

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const SKILLS_DIR = './skills';

// 스킬 목록 수집
const skills = fs.readdirSync(SKILLS_DIR)
  .filter(d => fs.statSync(path.join(SKILLS_DIR, d)).isDirectory())
  .filter(d => fs.existsSync(path.join(SKILLS_DIR, d, 'SKILL.md')));

if (skills.length === 0) {
  console.error('No skills found');
  process.exit(1);
}

// 주차 기반 로테이션 — 매주 다른 스킬
const weekNumber = Math.floor(Date.now() / (7 * 24 * 60 * 60 * 1000));
const skillName = skills[weekNumber % skills.length];
const skillPath = path.join(SKILLS_DIR, skillName, 'SKILL.md');
const original = fs.readFileSync(skillPath, 'utf-8');

console.log(`Target skill: ${skillName}`);

// Claude API 호출 — web_search 도구 포함
const response = await client.beta.messages.create({
  model: 'claude-opus-4-7',
  max_tokens: 4096,
  betas: ['web-search-2025-03-05'],
  tools: [{ type: 'web_search_20250305', name: 'web_search' }],
  messages: [{
    role: 'user',
    content: `You are enhancing a skill file for a Claude Code skills repository (nova-skills).
The repository covers: Next.js frontend, NestJS backend, React Three Fiber 3D, and AI agent protocols.

## Current Skill: ${skillName}

\`\`\`markdown
${original}
\`\`\`

## Task
1. Search for the latest updates, new patterns, or common mistakes in this skill's domain.
   Focus on: recent API changes, new best practices, real-world pitfalls developers hit.
2. Identify ONE specific enhancement that adds concrete value.
3. Make the minimal targeted change — one new section, one updated example, or 1–2 new Common Mistakes rows.

## Rules
- Frontmatter (name, description) must remain unchanged
- Description must start with "Use when..." — triggering conditions only, no workflow summary
- Write body content in Korean (existing language)
- No version notes (e.g., "> v1.1.0: Added X") inside the body
- One focused change only — do not rewrite the entire skill

Return ONLY the complete updated SKILL.md content with no explanation, no markdown fences.`
  }]
});

// 텍스트 블록만 추출
const updated = response.content
  .filter(b => b.type === 'text')
  .map(b => b.text)
  .join('')
  .trim();

// 변경 없으면 종료
if (!updated || updated === original.trim()) {
  console.log('No changes — skipping PR');
  fs.appendFileSync(process.env.GITHUB_OUTPUT ?? '/dev/null', 'changed=false\n');
  process.exit(0);
}

// 스킬 파일 덮어쓰기
fs.writeFileSync(skillPath, updated + '\n');
console.log(`Updated: ${skillPath}`);

// PR 본문 파일 작성 (multiline 안전)
const prBody = `## Weekly Skill Enhancement

**Skill:** \`${skillName}\`

Automatically enhanced with latest patterns and best practices via web search.

---
*Generated by [weekly-skill-enhancement workflow](../.github/workflows/weekly-skill-enhancement.yml)*`;

fs.writeFileSync('/tmp/pr-body.md', prBody);

// GitHub Actions output
const out = process.env.GITHUB_OUTPUT ?? '/dev/null';
fs.appendFileSync(out, `changed=true\n`);
fs.appendFileSync(out, `skill_name=${skillName}\n`);
